name: PR Build Action

on:
  pull_request:

  pull_request_target:
    types: [opened, synchronize]
  push:

permissions:
  contents: read

jobs:
  build-x86_64:
    name: Build x86_64
    runs-on: macos-14
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v4
    - name: Build x86_64
      run: ./scripts/build.sh build x86_64
      env:
        DEVELOPER_DIR: '/Applications/Xcode_16.1.app/Contents/Developer'
    # - name: find dest root
    #   run: ls -lR "/Users/runner/work/macSup2Srt/macSup2Srt"
    - uses: actions/upload-artifact@v4
      with:
        name: macSup2Srt_x86_64
        path: "/Users/runner/work/macSup2Srt/macSup2Srt/Release/**/macSup2Srt"
        overwrite: true
  build-arm64:
    name: Build arm64
    runs-on: macos-14
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v4
    - name: Build arm64
      run: ./scripts/build.sh build arm64
      env:
        DEVELOPER_DIR: '/Applications/Xcode_16.1.app/Contents/Developer'
    # - name: find dest root
    #   run: ls -lR "/Users/runner/work/macSup2Srt/macSup2Srt"
    - uses: actions/upload-artifact@v4
      with:
        name: macSup2Srt_arm64
        path: "/Users/runner/work/macSup2Srt/macSup2Srt/Release/**/macSup2Srt"
        overwrite: true