name: PR Build Action

on:
  pull_request:

  pull_request_target:
    types: [opened, synchronize]
  push:
  release:


permissions:
  contents: read

jobs:
  build-x86_64:
    name: Build x86_64
    runs-on: macos-14
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v4
    - name: Build x86_64
      run: ./scripts/build.sh build x86_64
      env:
        DEVELOPER_DIR: '/Applications/Xcode_16.1.app/Contents/Developer'
    - uses: actions/upload-artifact@v4
      with:
        name: macSup2Srt_x86_64
        path: "/Users/runner/work/macSup2Srt/macSup2Srt/Release/**/macSup2Srt"
        overwrite: true
        compression-level: 9
    # - name: find dest root
    #   run: ls -lR "/Users/runner/work/macSup2Srt/macSup2Srt"


  build-arm64:
    name: Build arm64
    runs-on: macos-14
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v4
    - name: Build arm64
      run: ./scripts/build.sh build arm64
      env:
        DEVELOPER_DIR: '/Applications/Xcode_16.1.app/Contents/Developer'

    - uses: actions/upload-artifact@v4
      with:
        name: macSup2Srt_arm64
        path: "/Users/runner/work/macSup2Srt/macSup2Srt/Release/**/macSup2Srt"
        overwrite: true
        compression-level: 9

  download:
    needs: [build-arm64, build-x86_64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      # with:
      #   path: my-artifact
      #   pattern: macSup2Srt_*
      #   merge-multiple: true
    - run: ls -R

    - uses: ncipollo/release-action@v1
      with:
        tag: release
        commit: v${{ github.sha }}
        artifacts: "*.*"